apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::720074446744:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1G6GMCFJLBKPQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::720074446744:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-30T10:16:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "16736"
  uid: c76164b1-fdca-407a-806f-34d1e1623f81
